# --- VIEW CONFIGURATION ---
# Options: CLI, GUI
view.type=GUI

# --- PERSISTENCE CONFIGURATION ---
# Options: mysql, csv
persistence.type=mysql

# --- DATABASE CONNECTION ---
db.url=jdbc:mysql://localhost:3306/decluttify
db.user=Decluttify
db.password=(DvD.msl28)
db.driver=com.mysql.cj.jdbc.Driver

# --- TEST ENVIRONMENT DATABASE CONNECTION ---
testdb.url=jdbc:mysql://localhost:3306/test_decluttify
testdb.user=Test_Decluttify
testdb.password=Test_Decluttify

# --- SECURITY
pepper=shared-secret