# --- VIEW CONFIGURATION ---
# Options: CLI, GUI
view.type=GUI

# --- PERSISTENCE CONFIGURATION ---
# Options: mysql, csv
persistence.type=csv

# --- DATABASE CONNECTION ---
db.url=jdbc:mysql://localhost:3306/Decluttify
db.user=Decluttify
db.password=(DvD.msl28)
db.driver=com.mysql.cj.jdbc.Driver

# --- SECURITY
pepper=shared-secret